### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by pattonw** [funkelab/again#7]
Here are a couple areas for improvement that have been identified:

- [ ] Usage/API #4
- [ ] Custom code  #1 
- [ ] Random seeds #6
- [ ] Data generalization #2
- [ ] Pipeline generalization #3
- [ ] Expand built in use cases #5
- [ ] Prediction #8
- [ ] Support large Validation volumes #9
- [ ] Support partial reruns #10

Things that would be nice to have:

- [ ] CI/CD github actions
- [ ] installation guide
- [x] basic usage tutorial
- [ ] customization/plugin tutorial
- [ ] tests
